### ISSUE TITLE
Omit Python 3.7 support

### ISSUE THREAD

**Issue by mberz** [pyfar/sofar#44]
Should we drop support for Python 3.7 with the next release, as we did in pyfar?

**Comment by f-brinkmann** [comment]
Yes, done it right away.

**Comment by davircarvalho** [comment]
Hi what's the reason from dropping support for python 3.7?

In `sofar==1.1.4`  if I manually revert the requirement back `>=3.7` and install the library in **python 3.7** the pytest outputs the same result as when I run the pytest using **python 3.10** .    

both give:
> 3 failed, 252 passed

So is there really a requirement that sofar needs **python>=3.8** as none of its dependencies seem to require python>=3.8 either?

I'm running an environment which unfortunately is locked to python 3.7 and comes in handy to use the binaries instead of the repo installation, would it be possible to revert this change and allow support for python>=3.7?

**Comment by f-brinkmann** [comment]
Hi Davi, we were dropping it because numpy did so in 1.22: https://numpy.org/devdocs/release/1.22.0-notes.html#. Is there a reason you can't install sofar<1.1.4 in your environment?

**Comment by davircarvalho** [comment]
I've been using Sofar 0.3.1, but I'd prefer to use updated binaries in case there are bug fixes, updates, and so on.

In Sofar's dependencies, it states 'numpy>=1.14.0'. However, considering that Sofar doesn't have a mandatory numpy>=1.22 requirement,  and it still passes the pytest in the same way with both:

- Python 3.10 with numpy 2.0.0
- Python 3.7 with numpy 1.21.6

Code-wise, there doesn't seem to be any reason not to support Python 3.7.

**Comment by f-brinkmann** [comment]
We decided to rather do it now than to wait for conflicts or bugs that require time critical action at a later point. So I think we will most likley not revert it. You could fork the repository, remove the restriction and install it locally using `pip install /your/path/to/sofar` - would that be a working soloution?
