### ISSUE TITLE
FreeFieldDirectivityTF for multiple sources 

### ISSUE THREAD

**Issue by ahms5** [pyfar/sofar#61]
Bug for convention ``FreeFieldDirectivityTF`` for multiple sources without/with Description

Here is a simple example
```
sofa = sf.Sofa('FreeFieldDirectivityTF')
source_position = np.arange(2*3).reshape(2, 3)
receiver_position = np.arange(1*3).reshape(1, 3)
frequencies = np.array([100, 200])
data = np.ones((2, 1, 2))
# Source and receiver data
sofa.SourcePosition = source_position
sofa.ReceiverPosition = receiver_position
sofa.Data_Real = np.real(data)
sofa.Data_Imag = np.imag(data)
sofa.N = np.array(frequencies).flatten()
sf.io.write_sofa(os.path.join(tmpdir, 'test.sofa'), sofa)
```

**Comment by f-brinkmann** [comment]
This behavior is intended and in agreement with the SOFA standard AES69-2022. If you want to provide a *Description* you can do so for example by
`sofa.Description = [['source1'], ['source2']]`
Since the field is optional (i.e. not mandatory in sofa language) you can also delete it if you do not want to provide these information
`sofa.delete('Description')`
