### ISSUE TITLE
Error reading  GeneralFIR v2.0 SOFA files created with sofar v0.3.1

### ISSUE THREAD

**Issue by alanpawlak** [pyfar/sofar#72]
## Description
Encountered a `ValueError` when trying to load SOFA files created with sofar version 0.3.1 using the latest version of sofar. These files load correctly in the official Matlab toolbox for SOFA and in sofar 0.3.1, indicating a potential issue with backward compatibility or file handling in the latest sofar version.

## Steps to Reproduce
1. Create a SOFA file using sofar 0.3.1 with the following code:
   ```python
   sofa = sofar.Sofa("GeneralFIR")
   ```
2. Attempt to load this file using the most recent version of sofar.

## Expected Behavior

The file should load without errors, maintaining compatibility with files created using older versions of sofar.

## Actual Behavior
Received a `ValueError indicating that "GeneralFIR v2.0 is not a valid SOFA Convention.` The error suggests using sofar.read_sofa_as_netcdf() and refers to sofar.list_conventions() for valid conventions. This is confusing as the file is valid and works with previous versions and the Matlab toolbox.

I double-checked, and in sofar 0.3.1, the command `sofa = sofar.Sofa("GeneralFIR")` creates a file with the GeneralFIR 2.0 convention. The same command in the most recent version results in a GeneralFIR 1.0.

**Comment by alanpawlak** [comment]
To resolve the issue, I manually changed the version, added the missing metadata, and then verified it. This approach seems to have fixed the problem, but I would appreciate any advice if there's anything I might have overlooked.

```
import os
import sofar

def read_sofa_files(directory):
    sofa_files = {}
    for filename in os.listdir(directory):
        if filename.endswith(".sofa"):
            file_path = os.path.join(directory, filename)
            sofa_object = sofar.read_sofa_as_netcdf(file_path)

            # Fix the sofa object
            sofa_object.GLOBAL_SOFAConventionsVersion = "1.0"
            sofa_object.add_attribute("GLOBAL_RoomDescription", "None")
            sofa_object.verify()
            sofa_files[os.path.splitext(filename)[0]] = sofa_object
    return sofa_files

def save_sofa_files(sofa_files, directory):

    if not os.path.exists(directory):
        os.makedirs(directory)

    for filename, sofa_object in sofa_files.items():
        file_path = os.path.join(directory, filename + ".sofa")
        sofar.write_sofa(file_path, sofa_object)

if __name__ == "__main__":
    sofa_files = read_sofa_files('ir')

    # Save
    save_sofa_files(sofa_files, 'new_ir')
```

**Comment by f-brinkmann** [comment]
Hi Alan, thanks for reporting. Under the hood sofar is using the convention files provided by the SOFAtoolbox. In many cases the released versions contain errors

- [Pull 31](https://github.com/sofacoustics/SOFAtoolbox/pull/31)
- [Issue 53](https://github.com/sofacoustics/SOFAtoolbox/issues/53)
- [Issue 67](https://github.com/sofacoustics/SOFAtoolbox/issues/67)
- [Issue 78](https://github.com/sofacoustics/SOFAtoolbox/issues/78)
 
At the moment, sofar is the only package that seriously tests, if a sofa file is in agreement with the sofa standard, which is why files that can not be read with sofar can often be read with other APIs, even if they contain formal errors. In your case, the version 2.0 was deleted at a later point. We added `read_sofa_as_netcdf` for exactly this purpose and I'm glad you found the 'easiest' way to solve the issue. We are cooperating with SOFAtoolbox to try to avoid these issues in the future. I edited the title of the issue in the hope this makes it easier to find if others have the same problem. Should we leave this open for documentation or close it?
